# name="Gangaprasad"
# age=23
# print(name,"\n",age)
# print(type(name))
# print(type(age))


#DATA TYPE
"""
INTEGER
STRING
FLOAT
BOOLEN (TRUE OR FALSE)
NONE  
"""
# age=19
# old=True
# a=None
# print(type(old))
# print(type(a))

# a=3
# b=4
# print(a+b)

# operators

# print(8+4)
# print(8-4)
# print(8*4)
# print(8/4)
# print(8%4)
# print(9//4)
# print(5**2)
# a=20
# b=40
# print(not False)
# print(not (a>b))

# #Q create a calculator
# a=int(input("first no."))
# b=int(input("second no."))
# print(a+b)
# print(a-b)
# print(a*b)
# print(a/b)
# print(a%b)
# print(a//b)
# print(a**b)

# TYPE CONVERSION(automatically) & TYPE CASTING(manual)
# a=2
# b=4.25
# sum=a+b #2.0+4.25
# print(sum)

# a=int("3")
# b=8
# print(a+b)

# a=3
# a=str(a)
# print(type(a)) # str

#  INPUT IN PYTHON 
# a=input("")
# b=int(input(""))

#Q write a program to input 2 numbers &print their sum
a=int(input("1"))
b=int(input("2"))
print(a+b)
